### ISSUE TITLE
Log model config not use in belongTo/hasMany

### ISSUE THREAD

**Issue by thomascombe** [akaunting/laravel-firewall#33]
Hi,

We can configure log model class in : https://github.com/akaunting/laravel-firewall/blob/master/src/Config/firewall.php#L11
```php
    'models' => [
        'user' => '\App\Models\User',
        // 'log' => '\App\Models\YourLogModel',
        // 'ip' => '\App\Models\YourIpModel',
    ],
```

But this config not use in `Ip` model for : 
* [log belongTo](https://github.com/akaunting/laravel-firewall/blob/master/src/Models/Ip.php#L20)
* [log hasMany](https://github.com/akaunting/laravel-firewall/blob/master/src/Models/Ip.php#L25)

**Comment by denisdulici** [comment]
Feel free to send a PR.
