### ISSUE TITLE
API return

### ISSUE THREAD

**Issue by robov** [akaunting/laravel-firewall#38]
Awesome package, and i really love it.
When an IP is blocked it shows nicely the "blocked" view

However, sometimes I call the backend through axios and then I get the view back in the console. Any suggestions what the best way of communication to the user is with API calls

As far as I can see in the code I cannot change the response based on a api call or a http call

Suggestion
Maybe in the middleware.php determine if the call was an api and then use different config parameters to return
then on a blocked api call the frontend can determine the error and show a message to the user / or redirect with js

**Comment by denisdulici** [comment]
Glad to see you like the package 😉 

I don't think there is an easy way to find if the request is an API call but feel free to send a PR for any kind of solution.
