### ISSUE TITLE
Issues with Validation messages and incorrect redirect in Laravel 9 Inertia.js Jetstream

### ISSUE THREAD

**Issue by ljsharp** [akaunting/laravel-firewall#63]
Hi, before installing this package, everything works okay with the validation messages and redirects to the intended location (URL). After doing some operations, I wanted it to be redirected to an intended URL but instead to a previous location with or without validation errors thrown. Also, the validation messages are like this: **validation.required**

**Comment by samehdoush** [comment]
because lang folder  #59

**Comment by denisdulici** [comment]
Fixed in the latest version.
