### ISSUE TITLE
Specify Queue for notification emails

### ISSUE THREAD

**Issue by horstoeko** [akaunting/laravel-firewall#65]
Hi Developer Team,

first of all thank you very much for this great package. My question: Can you create a way to be able to specify the name of the queue for sending the notification emails? Background: I use different queues, but never the queue "default".

Thanks a lot

HorstOeko

**Comment by denisdulici** [comment]
Feel free to submit such a PR.

**Comment by Hegabovic** [comment]
hello sir , slack notification is not working with me , is there a special configuration for it ?
